# Generated by Django 3.2.6 on 2023-07-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo_db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
